### ISSUE TITLE
Networking?

### ISSUE THREAD

**Issue by jarodium** [db48x/emularity#17]
Hello 

Have you ever tested a network game? Like Worms 1995( 7? ) ( IPX game ) a client to server connection in a browser? Maybe with some kind of WebRTC layer?

**Comment by db48x** [comment]
An excellent question. In fact we have played with this, although there's not as far as I know anything special for Emularity to do; it's all in how you compile the thing to be emulated.

DosBox has a nice feature that converts ATDT dial commands on an emulated modem into TCP connections (so that you can have your emulated modem software "dial" ATDTtowel.blinkenlights.nl and watch Starwars, for example). Emscripten can be convinced to convert raw TCP socket connections into WebSocket connections, and you can run a PPP server on any random VPS you want. Combine them all and you can get a real connection to the internet.

In fact, you can take a look at a Windows 3.11 emulation that my friend @jbaicoianu set up at <http://metacade.com/win311> which does all of this. And plays the modem sounds, for maximum nostalgia value.

He also runs all the HTTP traffic that comes from the emulator through an HTTP1.1 → HTTP0.9 proxy, so that Netscape and Mosiac actually work with modern web servers. A proxy that only lets you see webpages that the Wayback Machine has captured was discussed, but never implemented.

You can read more about it at <http://blog.vrcade.io/2017/03/setting-up-a-visp-using-pppow/>.
