### ISSUE TITLE
IALoader dosbox error?

### ISSUE THREAD

**Issue by sas1024** [db48x/emularity#29]
Hello!
I tried to load over IALoader some dos games. For example, with this: `var emulator = new IALoader(document.querySelector("#canvas"), "msdos_Alley_Cat_1984");`.
But i've got an HTTP error 503 with CORS.

But when I use this: `var emulator = new IALoader(document.querySelector("#canvas"), "msdos_Alley_Cat_1984/Alley_Cat_1984.zip");` all works fine.
May be it need to add detection of zip archives to `get_dosbox_files` function? Such as in `get_mame_files` function.

**Comment by db48x** [comment]
Good catch. `get_dosbox_files` needs to fall back to the `emulator_ext` metadata property on the item if there are no properties that match `^dosbox_drive[a-zA-Z]$`.

There are some other improvements I ought to make here as well; hopefully I can make the code clearer so that omssions such as this one are easier to spot.
