### ISSUE TITLE
Is there a way to store scores?

### ISSUE THREAD

**Issue by DanielBakovic** [db48x/emularity#66]
Hi,

Is there a way to store achieved scores on the site which hosts the games?

Regards
Daniel

**Comment by db48x** [comment]
Not directly. If the game files are loaded from a zip file, then any writes back to the emulated filesystem will be stored in the user's IndexedDB, if it is available. This can allow the user to reload a saved game, or see a top-10 list with their name in it. Otherwise any data written by the emulated item is lost when the page is reloaded.

However, there's no built-in mechanism to send that data back to the server. You can probably implement something like that yourself, but it'll have to be customized for every game you want to support.

**Comment by DanielBakovic** [comment]
Thx for the clarification 👍

**Comment by goyney** [comment]
I'm about to dive into this for a few more popular games. @DanielBakovic you didn't happen to make any progress with this in the meantime?
