### ISSUE TITLE
both async and sync fetching of the wasm failed

### ISSUE THREAD

**Issue by GWTRC** [db48x/emularity#80]
I keep getting these errors in my browser console when I try to run the example MAME page on the root of the repo:

(highlighted in red to indicate failure) GET http://\<my web domain\>/mame/emulators/jsmess/mameexidy.wasm
both async and sync fetching of the wasm failed

I followed the instructions in the example file's comments. I am EXTREMELY new to web development beyond basic HTML, so take it easy on me if I just didn't do something right please.

**Comment by db48x** [comment]
Thanks for using Emularity :)

Which error code does it report? Can you load that url in a tab by itself?

**Comment by leimao** [comment]
I got the same problem. The program is looking for http://0.0.0.0:8000/emulators/jsmess/mameexidy.wasm and obviously this file does not exist.

**Comment by JFCG4mer** [comment]
@db48x it throws a 404, and no the file does not exist in /emulators/jsmess/
<img width="549" alt="image" src="https://user-images.githubusercontent.com/70714444/197031950-2152ef5c-9e12-4448-aac0-a2251f517089.png">

**Comment by db48x** [comment]
A 404 error means that the server doesn’t have the file. The server needs to have the file, otherwise it won’t work. I don’t provide any of the emulators as part of this repository. You can either build them yourself (though I cannot really recommend that; it’s non–trivial), or you can download them from archive.org’s [emularity_engine_v1](http://archive.org/download/emularity_engine_v1) item. These are not necessarily updated on a regular schedule, but at the moment most of them appear to be fairly recently updated.
