### ISSUE TITLE
How to find specific files stored in annex

### ISSUE THREAD

**Issue by puntillol59** [db48x/emularity#81]
I'm new to annex, and i'm not sure if there is something I missed, but I need the em-dosbox .gz files. When I use git annex get for any of these files git annex says I need to add a remote (db48x@erebor:~/projects/emularity) but when I try to add it, git just exits with `usage: git remote add [<options>] <name> <url>`. What do I need to do to get these files. (I cannot compile em-dosbox due to me using a Windows machine.)

**Comment by puntillol59** [comment]
Nevermind, the example_dosbox.html file has links to them.

**Comment by db48x** [comment]
Yea, I should stop mentioning git-annex, or fix it. The original idea was that it would be easy to add urls to each annexed file so that folks such as yourself could download them from the Internet Archive. Unfortunately, that turned out not to be as easy as I had expected. I could perhaps automate it.

Thanks for using Emularity! Let me know if you need anything.

**Comment by leimao** [comment]
This is the first time I heard of `annex`. No wonder I was not able to pull them using `git-lfs`.

**Comment by leimao** [comment]
```bash
$ git-annex get
get emulators/em-dosbox/dosbox.js.gz (from web...) 
                                  
  verification of content failed

  Unable to access these remotes: web

  Maybe add some of these git remotes (git remote add ...):
  	877254f0-3c7c-451f-9eda-752bd3359fce -- db48x@erebor:~/projects/emularity

  (Note that these git remotes have annex-ignore set: origin)
failed
git-annex: get: 1 failed
```
