### ISSUE TITLE
how to implement?

### ISSUE THREAD

**Issue by dnelband** [db48x/emularity#9]
it always results in " Failed to download game data!", there is no working example anywhere i could find nor a guide how to implement - for example what should i put in the locateAdditionalFiles function? it would be great to even have a minimal explanation to the different emulators because without a working example in which i could at least inspect the code its unusable to anyone who doesnt understand it already.

**Comment by db48x** [comment]
Sorry for the delayed reply; I've been on a train. I see you've found example_dosbox.html. That's a good choice because it's the only one that has so far needed to use the locateAdditionalFiles option. I agree that so far the documentation is insufficient; I hope that between the examples and my help you can figure it out. Then we can update the documentation to explain things better.

**Comment by dosboxonline** [comment]
example_ia.html - Failed to download IA item metadata! example_console.html - Game File OK, Config File OK, black screen in Firefox, empty in Chrome. Also try upload on web server with primary links to all files. emulator mess js and game file downloaded from archive org. DOSBox-em work OK!

**Comment by db48x** [comment]
@dosboxonline, could you file a separate issue for your questions? Many thanks.

@dnelband, did you get Emularity working? If so, can this issue be closed?

**Comment by dosboxonline** [comment]
Yes. Thanks.

**Comment by db48x** [comment]
Excellent :)
